name: Deploy to Vercel

on:
  push:
    branches:
      - dev  # Change this to your dev branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x  # Adjust the Node.js version if needed

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build the Angular app
        run: ng build --prod

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@dev  # Use the main branch of the action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
